eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8764
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: firstModule
          uri: http://localhost:8100/associates/list
          predicates:
            - Path=/skill/**